<a href="https://colab.research.google.com/github/manojsankarkumar/manojsankarkumar.github.io/blob/master/Chapter_4_Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Chapter 4 - Task 2 - Coding

###### 1.	Write a program to take a name and age from the user and printing a greeting message.

In [ ]:
import datetime

def greeting_of_day():
    try:
        name = input("Enter your name: ")
        age = int(input("Enter your age: "))

        hour = datetime.datetime.now().hour

        if hour < 12:
            greeting = "Good Morning"
        elif hour < 17:
            greeting = "Good Afternoon"
        elif hour < 21:
            greeting = "Good Evening"
        else:
            greeting = "Good Night"

        print(f"{greeting}, {name} of age {age}. We welcome you to this course!")

    except ValueError:
        print("Error: Age must be a valid number!")

greeting_of_day()

Enter your name: MK
Enter your age: 33
Good Morning, MK of age 33. We welcome you to this course!

######  2.	Create a list of numbers and print only even numbers using  a for loop

In [ ]:
numbers_list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]

even_numbers = []

for num in numbers_list:
    if num % 2 == 0:
      even_numbers.append(num)

print("Even numbers:", even_numbers)

Even numbers: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

######  3. Write a program that handles division by zero using try-except

In [ ]:
def num_to_divide():
  try:
    num = int(input("Enter the number to be divided by zero:"))
    result = num / 0
    print(result)
  except ZeroDivisionError:
    print("Error! Value given is not divided by zero")

num_to_divide()

Enter the number to be divided by zero:1
Error! Value given is not divided by zero

###### 4.	Given a string, count how many vowels it has.

In [ ]:
def count_vowels():
  try:
      string = input("Enter a name:")
      vowels = ["a","e","i","o","u","A","E","I","O","U"]
      count = 0

      for char in string:
        if char in vowels:
          count += 1

      print("Count of vowels:", count)
  except ValueError:
      print("Enter a valid name")
count_vowels()

Enter a name:manoj kumar
Count of vowels: 4

###### 5.	Review a list without using built-in functions

In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]

# Length
count = 0
for num in numbers:
    count += 1
print("Count:",count)

# Sum
total = 0
for num in numbers:
    total += num
print("Total:", total)

# Largest
largest = numbers[0]
for num in numbers:
    if num > largest:
        largest = num
print("Largest:",largest)

# Smallest
smallest = numbers[0]
for num in numbers:
    if num < smallest:
        smallest = num
print("Smallest:",smallest)

Count: 30
Total: 465
Largest: 30
Smallest: 1

###### 6.	Create a dict with at least 5 key-value pairs and print them

In [79]:
import pandas as pd

student_details = {"Name " : " Manoj Kumar",
                   "Department " : " Automobile",
                   "College " : " REC",
                   "Roll Number " : 2114567,
                   "Year of Completion " : 2015}

for key,value in student_details.items():
  print(f"{key}:{value}")

Name : Manoj Kumar
Department : Automobile
College : REC
Roll Number :2114567
Year of Completion :2015

###### 7.	Write a pandas code to read a CSV and print the top 5 rows

In [82]:
import pandas as pd

sales_2017 = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales Transactions-2017.csv")
sales_2017

#print the top 5 rows
sales_2017.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN

###### 8.	Create a DataFrame from a Python dictionary

In [90]:
import pandas as pd

student_details = {"Name" : ["Manoj Kumar"],
                   "Department" : ["Automobile"],
                   "College" : ["REC"],
                   "Roll Number" : [2114567],
                   "Year of Completion " : [2015]}

student_detail_df = pd.DataFrame(student_details)
print(student_detail_df)

          Name  Department College  Roll Number  Year of Completion
0  Manoj Kumar  Automobile     REC      2114567                 2015

###### 9.	Replace all missing values in a DataFrame with the column’s mean

In [48]:
import pandas as pd

employee_data = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Employee_data.csv")
employee_data

employee_data['Salary'].fillna(value=employee_data['Salary'].mean(),inplace=True)

employee_data

/tmp/ipykernel_1164/3863532500.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employee_data['Salary'].fillna(value=employee_data['Salary'].mean(),inplace=True)

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

###### 10.	Filter rows in a DataFrame where ‘Age’ column is greater than 30.

In [10]:
import pandas as pd

#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

"""emp_data = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Employee_data.csv")
emp_data = emp_data.dropna()
emp_data

#Filter where Age is greater than 30 - 1st example

filtered_emp = emp_data[emp_data['Age'] > 30]
filtered_emp"""

insurance_data = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Insurance.csv")

#Filter where Age is greater than 30 - 2nd example
filtered_person_by_age = insurance_data[insurance_data['age'] > 30]
filtered_person_by_age

      age     sex     bmi  children smoker     region      charges
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
7      37  female  27.740         3     no  northwest   7281.50560
8      37    male  29.830         2     no  northeast   6406.41070
9      60  female  25.840         0     no  northwest  28923.13692
11     62  female  26.290         0    yes  southeast  27808.72510
13     56  female  39.820         0     no  southeast  11090.71780
16     52  female  30.780         1     no  northeast  10797.33620
18     56    male  40.300         0     no  southwest  10602.38500
20     60  female  36.005         0     no  northeast  13228.84695
23     34  female  31.920         1    yes  northeast  37701.87680
24     37    male  28.025         2     no  northwest   6203.90175
25     59  female  27.720         3     no  southeast  14001.13380
26     63  female  23.085         0     no  northeast  14451.83515
27     55  female  32.775         2     no  northwest  12268.63225
29     31    male  36.300         2    yes  southwest  38711.00000
33     63    male  28.310         0     no  northwest  13770.09790
36     62  female  32.965         3     no  northwest  15612.19335
38     35    male  36.670         1    yes  northeast  39774.27630
39     60    male  39.900         0    yes  southwest  48173.36100
41     31  female  36.630         2     no  southeast   4949.75870
42     41    male  21.780         1     no  southeast   6272.47720
43     37  female  30.800         2     no  southeast   6313.75900
44     38    male  37.050         1     no  northeast   6079.67150
45     55    male  37.300         0     no  southwest  20630.28351
48     60  female  24.530         0     no  southeast  12629.89670
49     36    male  35.200         1    yes  southeast  38709.17600
52     48    male  28.000         1    yes  southwest  23568.27200
53     36    male  34.430         0    yes  southeast  37742.57570
54     40  female  28.690         3     no  northwest   8059.67910
55     58    male  36.955         2    yes  northwest  47496.49445
56     58  female  31.825         2     no  northeast  13607.36875
58     53  female  22.880         1    yes  southeast  23244.79020
59     34  female  37.335         2     no  northwest   5989.52365
60     43    male  27.360         3     no  northeast   8606.21740
62     64    male  24.700         1     no  northwest  30166.61817
66     61  female  39.100         2     no  southwest  14235.07200
67     40    male  26.315         1     no  northwest   6389.37785
68     40  female  36.190         0     no  southeast   5920.10410
71     31    male  28.500         5     no  northeast   6799.45800
72     53  female  28.100         3     no  southwest  11741.72600
73     58    male  32.010         1     no  southeast  11946.62590
74     44    male  27.400         2     no  southwest   7726.85400
75     57    male  34.010         0     no  northwest  11356.66090
79     41  female  32.965         0     no  northwest   6571.02435
80     31    male  26.885         1     no  northeast   4441.21315
81     45  female  38.285         0     no  northeast   7935.29115
83     48  female  41.230         4     no  northwest  11033.66170
84     37  female  34.800         2    yes  southwest  39836.51900
85     45    male  22.895         2    yes  northwest  21098.55405
86     57  female  31.160         0    yes  northwest  43578.93940
87     56  female  27.200         0     no  southwest  11073.17600
88     46  female  27.740         0     no  northwest   8026.66660
89     55  female  26.980         0     no  northwest  11082.57720
91     53  female  24.795         1     no  northwest  10942.13205
92     59    male  29.830         3    yes  northeast  30184.93670
93     35    male  34.770         2     no  northwest   5729.00530
94     64  female  31.300         2    yes  southwest  47291.05500
96     54  female  30.800         3     no  southwest  12105.32000
97     55    male  38.280         0     no  southeast  10226.28420
98     56    male  19.950         0    yes  northeast  22412.64850
99     38    male  19.300         0    yes  southwest  15820.69900
100    41  female  31.600         0     no  southwest   6186.12700
103    61  female  29.920         3    yes  southeast  30942.19180
104    34  female  27.500         1     no  southwest   5003.85300
109    63    male  35.090         0    yes  southeast  47055.53210
110    54    male  33.630         1     no  northwest  10825.25370
111    55  female  29.700         2     no  southwest  11881.35800
112    37    male  30.800         0     no  southwest   4646.75900
114    52    male  32.205         3     no  northeast  11488.31695
115    60    male  28.595         0     no  northeast  30259.99556
116    58    male  49.060         0     no  southeast  11381.32540
118    49  female  27.170         0     no  southeast   8601.32930
119    37  female  23.370         2     no  northwest   6686.43130
120    44    male  37.100         2     no  southwest   7740.33700
123    44    male  31.350         1    yes  northeast  39556.49450
124    47  female  33.915         3     no  northwest  10115.00885
127    52  female  37.400         0     no  southwest   9634.53800
128    32  female  17.765         2    yes  northwest  32734.18630
129    38    male  34.700         2     no  southwest   6082.40500
130    59  female  26.505         0     no  northeast  12815.44495
131    61  female  22.040         0     no  northeast  13616.35860
132    53  female  35.900         2     no  southwest  11163.56800
138    54  female  31.900         3     no  southeast  27322.73386
140    34    male  22.420         2     no  northeast  27375.90478
142    34    male  25.300         2    yes  southeast  18972.49500
146    46    male  30.495         3    yes  northwest  40720.55105
147    51  female  37.730         1     no  southeast   9877.60770
148    53  female  37.430         1     no  northwest  10959.69470
150    35    male  24.130         1     no  northwest   5125.21570
151    48    male  29.700         0     no  southeast   7789.63500
152    32  female  37.145         3     no  northeast   6334.34355
153    42  female  23.370         0    yes  northeast  19964.74630
154    40  female  25.460         1     no  northeast   7077.18940
155    44    male  39.520         0     no  northwest   6948.70080
156    48    male  24.420         0    yes  southeast  21223.67580
159    50  female  27.830         3     no  southeast  19749.38338
160    42  female  26.600         0    yes  northwest  21348.70600
162    54    male  39.600         1     no  southwest  10450.55200
163    32  female  29.800         2     no  southwest   5152.13400
164    37    male  29.640         0     no  northwest   5028.14660
165    47    male  28.215         4     no  northeast  10407.08585
167    32  female  33.155         3     no  northwest   6128.79745
170    63    male  41.470         0     no  southeast  13405.39030
171    49    male  30.300         0     no  southwest   8116.68000
173    35  female  34.800         1     no  southwest   5246.04700
175    63  female  37.700         0    yes  southwest  48824.45000
176    38    male  27.835         2     no  northwest   6455.86265
177    54    male  29.200         1     no  southwest  10436.09600
178    46  female  28.900         2     no  southwest   8823.27900
179    41  female  33.155         3     no  northeast   8538.28845
180    58    male  28.595         0     no  northwest  11735.87905
183    44  female  26.410         0     no  northwest   7419.47790
184    44    male  30.690         2     no  southeast   7731.42710
185    36    male  41.895         3    yes  northeast  43753.33705
188    41  female  32.200         1     no  southwest   6775.96100
190    61    male  31.570         0     no  southeast  12557.60530
191    36  female  26.200         0     no  southwest   4883.86600
193    56  female  26.600         1     no  northwest  12044.34200
196    39  female  32.800         0     no  southwest   5649.71500
197    45  female  28.600         2     no  southeast   8516.82900
198    51  female  18.050         0     no  northwest   9644.25250
199    64  female  39.330         0     no  northeast  14901.51670
201    48  female  32.230         1     no  southeast   8871.15170
202    60  female  24.035         0     no  northwest  13012.20865
204    46    male  22.300         0     no  southwest   7147.10500
206    59    male  26.400         0     no  southeast  11743.29900
207    35    male  27.740         2    yes  northeast  20984.09360
208    63  female  31.800         0     no  southwest  13880.94900
209    40    male  41.230         1     no  northeast   6610.10970
211    40    male  30.875         4     no  northwest   8162.71625
213    34  female  26.730         1     no  southeast   5002.78270
214    45  female  30.900         2     no  southwest   8520.02600
215    41  female  37.100         2     no  southwest   7371.77200
216    53  female  26.600         0     no  northwest  10355.64100
220    34  female  33.700         1     no  southwest   5012.47100
221    53  female  33.250         0     no  northeast  10564.88450
222    32    male  30.800         3     no  southwest   5253.52400
224    42    male  24.640         0    yes  southeast  19515.54160
225    55    male  33.880         3     no  southeast  11987.16820
227    58  female  41.910         0     no  southeast  24227.33724
228    41  female  31.635         1     no  northeast   7358.17565
229    47    male  25.460         2     no  northeast   9225.25640
230    42  female  36.195         1     no  northwest   7443.64305
231    59  female  27.830         3     no  southeast  14001.28670
233    59    male  27.500         1     no  southwest  12333.82800
234    39    male  24.510         2     no  northwest   6710.19190
235    40  female  22.220         2    yes  southeast  19444.26580
237    31    male  38.390         2     no  southeast   4463.20510
239    44    male  38.060         1     no  southeast   7152.67140
241    33  female  22.135         1     no  northeast   5354.07465
242    55  female  26.800         1     no  southwest  35160.13457
243    40    male  35.300         3     no  southwest   7196.86700
244    63  female  27.740         0    yes  northeast  29523.16560
245    54    male  30.020         0     no  northwest  24476.47851
246    60  female  38.060         0     no  southeast  12648.70340
251    63  female  32.200         2    yes  southwest  47305.30500
252    54    male  34.210         2    yes  southeast  44260.74990
254    50    male  31.825         0    yes  northeast  41097.16175
255    55  female  25.365         3     no  northeast  13047.33235
256    56    male  33.630         0    yes  northwest  43921.18370
257    38  female  40.150         0     no  southeast   5400.98050
258    51    male  24.415         4     no  northwest  11520.09985
260    58  female  25.200         0     no  southwest  11837.16000
262    52    male  24.320         3    yes  northeast  24869.83680
264    53  female  38.060         3     no  southeast  20462.99766
265    46    male  42.350         3    yes  southeast  46151.12450
266    40    male  19.800         1    yes  southeast  17179.52200
267    59  female  32.395         3     no  northeast  14590.63205
268    45    male  30.200         1     no  southwest   7441.05300
269    49    male  25.840         1     no  northeast   9282.48060
271    50    male  34.200         2    yes  southwest  42856.83800
272    41    male  37.050         2     no  northwest   7265.70250
273    50    male  27.455         1     no  northeast   9617.66245
275    47  female  26.600         2     no  northeast   9715.84100
278    59    male  31.790         2     no  southeast  12928.79110
279    51  female  21.560         1     no  southeast   9855.13140
280    40  female  28.120         1    yes  northeast  22331.56680
281    54    male  40.565         3    yes  northeast  48549.17835
283    55  female  32.395         1     no  northeast  11879.10405
284    52  female  31.200         0     no  southwest   9625.92000
285    46    male  26.620         1     no  southeast   7742.10980
286    46  female  48.070         2     no  northeast   9432.92530
287    63  female  26.220         0     no  northwest  14256.19280
288    59  female  36.765         1    yes  northeast  47896.79135
289    52    male  26.400         3     no  southeast  25992.82104
297    47    male  25.410         1    yes  southeast  21978.67690
298    31    male  34.390         3    yes  northwest  38746.35510
299    48  female  28.880         1     no  northwest   9249.49520
300    36    male  27.550         3     no  northeast   6746.74250
301    53  female  22.610         3    yes  northeast  24873.38490
302    56  female  37.510         2     no  southeast  12265.50690
304    57  female  38.000         2     no  southwest  12646.20700
308    58    male  34.865         0     no  northeast  11944.59435
309    41  female  33.060         2     no  northwest   7749.15640
310    50    male  26.600         0     no  southwest   8444.47400
312    43    male  35.970         3    yes  southeast  42124.51530
313    49    male  35.860         0     no  southeast   8124.40840
315    52    male  33.250         0     no  northeast   9722.76950
316    50    male  32.205         0     no  northwest   8835.26495
317    54    male  32.775         0     no  northeast  10435.06525
318    44  female  27.645         0     no  northwest   7421.19455
319    32    male  37.335         1     no  northeast   4667.60765
320    34    male  25.270         1     no  northwest   4894.75330
322    34    male  30.800         0    yes  southwest  35491.64000
323    57    male  40.945         0     no  northeast  11566.30055
325    40    male  34.105         1     no  northeast   6600.20595
327    45    male  36.480         2    yes  northwest  42760.50220
328    64  female  33.800         1    yes  southwest  47928.03000
329    52    male  36.700         0     no  southwest   9144.56500
330    61  female  36.385         1    yes  northeast  48517.56315
331    52    male  27.360         0    yes  northwest  24393.62240
332    61  female  31.160         0     no  northwest  13429.03540
333    56  female  28.785         0     no  northeast  11658.37915
334    43  female  35.720         2     no  northeast  19144.57652
335    64    male  34.500         0     no  southwest  13822.80300
336    60    male  25.740         0     no  southeast  12142.57860
337    62    male  27.550         1     no  northwest  13937.66650
338    50    male  32.300         1    yes  northeast  41919.09700
339    46  female  27.720         1     no  southeast   8232.63880
341    62    male  30.020         0     no  northwest  13352.09980
342    60  female  27.550         0     no  northeast  13217.09450
343    63    male  36.765         0     no  northeast  13981.85035
344    49  female  41.470         4     no  southeast  10977.20630
345    34  female  29.260         3     no  southeast   6184.29940
346    33    male  35.750         2     no  southeast   4889.99950
347    46    male  33.345         1     no  northeast   8334.45755
348    36  female  29.920         1     no  southeast   5478.03680
350    57  female  23.180         0     no  northwest  11830.60720
351    50  female  25.600         0     no  southwest   8932.08400
353    33    male  35.245         0     no  northeast  12404.87910
355    46    male  27.600         0     no  southwest  24603.04837
356    46    male  43.890         3     no  southeast   8944.11510
357    47    male  29.830         3     no  northwest   9620.33070
360    48  female  32.300         2     no  northeast  10043.24900
361    35    male  30.500         1     no  southwest   4751.07000
365    49  female  30.780         1     no  northeast   9778.34720
366    56  female  32.300         3     no  northeast  13430.26500
367    42  female  24.985         2     no  northwest   8017.06115
368    44    male  32.015         2     no  northwest   8116.26885
370    61  female  21.090         0     no  northwest  13415.03810
371    57  female  22.230         0     no  northeast  12029.28670
372    42  female  33.155         1     no  northeast   7639.41745
376    39  female  24.890         3    yes  northeast  21659.93010
378    64  female  30.115         3     no  northwest  16455.70785
379    62    male  31.460         1     no  southeast  27000.98473
381    55    male  30.685         0    yes  northeast  42303.69215
382    55    male  33.000         0     no  southeast  20781.48892
383    35  female  43.340         2     no  southeast   5846.91760
384    44    male  22.135         2     no  northeast   8302.53565
386    58  female  39.050         0     no  southeast  11856.41150
387    50    male  25.365         2     no  northwest  30284.64294
390    48    male  35.625         4     no  northeast  10736.87075
392    48    male  31.445         1     no  northeast   8964.06055
393    49    male  31.350         1     no  northeast   9290.13950
394    46  female  32.300         2     no  northeast   9411.00500
395    46    male  19.855         0     no  northwest   7526.70645
396    43  female  34.400         3     no  southwest   8522.00300
398    64    male  25.600         2     no  southwest  14988.43200
400    51  female  20.600         0     no  southwest   9264.79700
401    47    male  47.520         1     no  southeast   8083.91980
402    64  female  32.965         0     no  northwest  14692.66935
403    49    male  32.300         3     no  northwest  10269.46000
404    31    male  20.400         0     no  southwest   3260.19900
405    52  female  38.380         2     no  northeast  11396.90020
406    33  female  24.310         0     no  southeast   4185.09790
407    47  female  23.600         1     no  southwest   8539.67100
408    38    male  21.120         3     no  southeast   6652.52880
409    32    male  30.030         1     no  southeast   4074.45370
411    44  female  20.235         1    yes  northeast  19594.80965
415    43  female  35.640         1     no  southeast   7345.72660
416    52    male  34.100         0     no  southeast   9140.95100
417    36  female  22.600         2    yes  southwest  18608.26200
418    64    male  39.160         1     no  southeast  14418.28040
419    63  female  26.980         0    yes  northwest  28950.46920
420    64    male  33.880         0    yes  southeast  46889.26120
421    61    male  35.860         0    yes  southeast  46599.10840
422    40    male  32.775         1    yes  northeast  39125.33225
424    48    male  30.200         2     no  southwest   8968.33000
425    45    male  24.310         5     no  southeast   9788.86590
426    38  female  27.265         1     no  northeast   6555.07035
432    42    male  26.900         0     no  southwest   5969.72300
433    60  female  30.500         0     no  southwest  12638.19500
434    31    male  28.595         1     no  northwest   4243.59005
435    60    male  33.110         3     no  southeast  13919.82290
437    35    male  28.900         3     no  southwest   5926.84600
438    52  female  46.750         5     no  southeast  12592.53450
440    31  female  32.680         1     no  northwest   4738.26820
441    33  female  33.500         0    yes  southwest  37079.37200
443    59  female  36.520         1     no  southeast  28287.89766
444    56    male  26.695         1    yes  northwest  26109.32905
445    45  female  33.100         0     no  southwest   7345.08400
446    60    male  29.640         0     no  northeast  12730.99960
447    56  female  25.650         0     no  northwest  11454.02150
448    40  female  29.600         0     no  southwest   5910.94400